require("manonaid.remap")
print([[                                                            .-.__      \ .-.  ___  __]])
print([[                                                            |_|  '--.-.-(   \/\;;\_\.-._______.-.]])
print([[                                                            (-)___     \ \ .-\ \;;\(   \       \ \]])
print([[                                                             Y    '---._\_((Q)) \;;\\ .-\     __(_)]])
print([[                                                             I           __'-' / .--.((Q))---'    \,]])
print([[                                                             I     ___.-:    \|  |   \'-'_          \]])
print([[                                                             A  .-'      \ .-.\   \   \ \ '--.__     '\]])
print([[                                                             |  |____.----((Q))\   \__|--\_      \     ']])
print([[                                                                ( )        '-'  \_  :  \-' '--.___\]])
print([[                                                                 Y                \  \  \       \(_)]])
print([[                                                                 I                 \  \  \         \,]])
print([[                                                                 I                  \  \  \          \]])
print([[                                                                 A                   \  \  \          '\]])
print([[                                                                 |              snd   \  \__|           ']])
print([[                                                                                       \_:.  \]])
print([[                                                                                         \ \  \]])
print([[                                                                                          \ \  \]])
print([[                                                                                           \_\_|]])

print(" ")
print(" ")
print("                              <|<|<| In a dark place we find ourselves, and a little more knowledge lights our way. |>|>|> ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
